services:
  - type: web
    name: gamedle
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 24.18.1
