import { VideoGame } from './video-game.model';

export const VIDEO_GAMES: VideoGame[] = [
  { id: 1, genre: 'Platformer', title: 'Super Mario Bros.', releaseYear: 1985, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 2, genre: 'Adventure', title: 'The Legend of Zelda', releaseYear: 1986, platforms: ['NES'], localMaximumPlayers: 1 },
  { id: 3, genre: 'Platformer', title: 'Super Mario Bros. 2', releaseYear: 1988, platforms: ['NES'], localMaximumPlayers: 1 },
  { id: 4, genre: 'Platformer', title: 'Super Mario Bros. 3', releaseYear: 1988, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 5, genre: 'Puzzle', title: 'Tetris', releaseYear: 1984, platforms: ['NES', 'Game Boy', 'PC'], localMaximumPlayers: 2 },
  { id: 6, genre: 'Platformer', title: 'Super Mario World', releaseYear: 1990, platforms: ['SNES'], localMaximumPlayers: 2 },
  { id: 7, genre: 'Action', title: 'The Legend of Zelda: A Link to the Past', releaseYear: 1991, platforms: ['SNES'], localMaximumPlayers: 1 },
  { id: 8, genre: 'Fighting', title: 'Street Fighter II', releaseYear: 1991, platforms: ['SNES'], localMaximumPlayers: 2 },
  { id: 9, genre: 'Platformer', title: 'Sonic the Hedgehog', releaseYear: 1991, platforms: ['Sega Genesis'], localMaximumPlayers: 1 },
  { id: 10, genre: 'Platformer', title: 'Donkey Kong Country', releaseYear: 1994, platforms: ['SNES'], localMaximumPlayers: 2 },
  { id: 11, genre: 'Role-Playing', title: 'Chrono Trigger', releaseYear: 1995, platforms: ['SNES'], localMaximumPlayers: 1 },
  { id: 12, genre: 'Role-Playing', title: 'EarthBound', releaseYear: 1995, platforms: ['SNES'], localMaximumPlayers: 1 },
  { id: 13, genre: 'Fighting', title: 'Mortal Kombat', releaseYear: 1992, platforms: ['SNES', 'Sega Genesis'], localMaximumPlayers: 2 },
  { id: 14, genre: 'Platformer', title: 'Super Mario 64', releaseYear: 1996, platforms: ['Nintendo 64'], localMaximumPlayers: 1 },
  { id: 15, genre: 'Adventure', title: 'The Legend of Zelda: Ocarina of Time', releaseYear: 1998, platforms: ['Nintendo 64'], localMaximumPlayers: 1 },
  { id: 16, genre: 'Platformer', title: 'Star Fox', releaseYear: 1993, platforms: ['SNES'], localMaximumPlayers: 1 },
  { id: 17, genre: 'Racing', title: 'F-Zero', releaseYear: 1990, platforms: ['SNES'], localMaximumPlayers: 1 },
  { id: 18, genre: 'Racing', title: 'Mario Kart 64', releaseYear: 1996, platforms: ['Nintendo 64'], localMaximumPlayers: 4 },
  { id: 19, genre: 'Fighting', title: 'Super Smash Bros.', releaseYear: 1999, platforms: ['Nintendo 64'], localMaximumPlayers: 4 },
  { id: 20, genre: 'Platformer', title: 'Kirby\'s Dream Land', releaseYear: 1992, platforms: ['Game Boy'], localMaximumPlayers: 1 },
  { id: 21, genre: 'Action', title: 'Metroid', releaseYear: 1986, platforms: ['NES'], localMaximumPlayers: 1 },
  { id: 22, genre: 'Action', title: 'Metroid Prime', releaseYear: 2002, platforms: ['GameCube'], localMaximumPlayers: 1 },
  { id: 23, genre: 'Action', title: 'Resident Evil 4', releaseYear: 2005, platforms: ['GameCube', 'PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 1 },
  { id: 24, genre: 'Survival horror', title: 'Silent Hill 2', releaseYear: 2001, platforms: ['PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 1 },
  { id: 25, genre: 'Platformer', title: 'Crash Bandicoot', releaseYear: 1996, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 26, genre: 'Platformer', title: 'Spyro the Dragon', releaseYear: 1998, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 27, genre: 'Role-Playing', title: 'Final Fantasy VII', releaseYear: 1997, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 1 },
  { id: 28, genre: 'Action', title: 'Metal Gear Solid', releaseYear: 1998, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 29, genre: 'Racing', title: 'Gran Turismo', releaseYear: 1997, platforms: ['PlayStation'], localMaximumPlayers: 2 },
  { id: 30, genre: 'Sandbox', title: 'Grand Theft Auto: San Andreas', releaseYear: 2004, platforms: ['PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 1 },
  { id: 31, genre: 'Sandbox', title: 'Grand Theft Auto V', releaseYear: 2013, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 32, genre: 'Adventure', title: 'Red Dead Redemption 2', releaseYear: 2018, platforms: ['PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 1 },
  { id: 33, genre: 'Action', title: 'The Legend of Zelda: Breath of the Wild', releaseYear: 2017, platforms: ['Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 34, genre: 'Action', title: 'The Legend of Zelda: Tears of the Kingdom', releaseYear: 2023, platforms: ['Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 35, genre: 'Role-Playing', title: 'The Witcher 3: Wild Hunt', releaseYear: 2015, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 36, genre: 'Sports', title: 'FIFA 22', releaseYear: 2021, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 4 },
  { id: 37, genre: 'First-person shooter', title: 'Overwatch', releaseYear: 2016, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 38, genre: 'Social simulation', title: 'Animal Crossing: New Horizons', releaseYear: 2020, platforms: ['Nintendo Switch'], localMaximumPlayers: 4 },
  { id: 39, genre: 'Role-Playing', title: 'Cyberpunk 2077', releaseYear: 2020, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 40, genre: 'Platformer', title: 'Super Mario Odyssey', releaseYear: 2017, platforms: ['Nintendo Switch'], localMaximumPlayers: 2 },
  { id: 41, genre: 'First-person shooter', title: 'Call of Duty: Modern Warfare', releaseYear: 2019, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 4 },
  { id: 42, genre: 'Sandbox', title: 'Minecraft', releaseYear: 2011, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'], localMaximumPlayers: 4 },
  { id: 43, genre: 'Action', title: 'Fortnite', releaseYear: 2017, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'], localMaximumPlayers: 4 },
  { id: 44, genre: 'First-person shooter', title: 'Half-Life', releaseYear: 1998, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 45, genre: 'First-person shooter', title: 'Half-Life 2', releaseYear: 2004, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 46, genre: 'Puzzle', title: 'Portal', releaseYear: 2007, platforms: ['PC', 'Xbox', 'PlayStation'], localMaximumPlayers: 1 },
  { id: 47, genre: 'Puzzle', title: 'Portal 2', releaseYear: 2011, platforms: ['PC', 'Xbox', 'PlayStation'], localMaximumPlayers: 2 },
  { id: 48, genre: 'First-person shooter', title: 'Counter-Strike', releaseYear: 2000, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 49, genre: 'First-person shooter', title: 'DOOM', releaseYear: 1993, platforms: ['PC'], localMaximumPlayers: 4 },
  { id: 50, genre: 'First-person shooter', title: 'Halo: Combat Evolved', releaseYear: 2001, platforms: ['Xbox', 'PC'], localMaximumPlayers: 4 },
  { id: 51, genre: 'First-person shooter', title: 'Left 4 Dead 2', releaseYear: 2009, platforms: ['PC', 'Xbox'], localMaximumPlayers: 4 },
  { id: 52, genre: 'First-person shooter', title: 'Team Fortress 2', releaseYear: 2007, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 53, genre: 'Role-Playing', title: 'BioShock', releaseYear: 2007, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 54, genre: 'Role-Playing', title: 'The Elder Scrolls V: Skyrim', releaseYear: 2011, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 55, genre: 'Role-Playing', title: 'Fallout 4', releaseYear: 2015, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 56, genre: 'Strategy', title: 'StarCraft', releaseYear: 1998, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 57, genre: 'Role-Playing', title: 'Diablo II', releaseYear: 2000, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 58, genre: 'Role-Playing', title: 'World of Warcraft', releaseYear: 2004, platforms: ['PC'], localMaximumPlayers: 1 },
  { id: 59, genre: 'Party', title: 'Overcooked! 2', releaseYear: 2018, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 4 },
  { id: 60, genre: 'Adventure', title: 'It Takes Two', releaseYear: 2021, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 2 },
  { id: 61, genre: 'Party', title: 'Mario Party', releaseYear: 1998, platforms: ['Nintendo 64'], localMaximumPlayers: 4 },
  { id: 62, genre: 'Party', title: 'Wii Sports', releaseYear: 2006, platforms: ['Nintendo Wii'], localMaximumPlayers: 4 },
  { id: 63, genre: 'Rhythm', title: 'Just Dance', releaseYear: 2009, platforms: ['Nintendo Wii', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 6 },
  { id: 64, genre: 'Rhythm', title: 'Guitar Hero III: Legends of Rock', releaseYear: 2007, platforms: ['PlayStation', 'Xbox', 'Nintendo Wii'], localMaximumPlayers: 2 },
  { id: 65, genre: 'Rhythm', title: 'Rock Band', releaseYear: 2007, platforms: ['PlayStation', 'Xbox', 'Nintendo Wii'], localMaximumPlayers: 4 },
  { id: 66, genre: 'Action', title: 'Pac-Man', releaseYear: 1980, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 67, genre: 'Action', title: 'Donkey Kong', releaseYear: 1981, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 68, genre: 'Action', title: 'Mega Man 2', releaseYear: 1988, platforms: ['NES'], localMaximumPlayers: 1 },
  { id: 69, genre: 'Action', title: 'Castlevania', releaseYear: 1986, platforms: ['NES'], localMaximumPlayers: 1 },
  { id: 70, genre: 'Action', title: 'Contra', releaseYear: 1987, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 71, genre: 'Sports', title: 'Punch-Out!!', releaseYear: 1987, platforms: ['NES'], localMaximumPlayers: 2 },
  { id: 72, genre: 'Adventure', title: 'Pikmin', releaseYear: 2001, platforms: ['GameCube'], localMaximumPlayers: 1 },
  { id: 73, genre: 'Action', title: 'Splatoon 2', releaseYear: 2017, platforms: ['Nintendo Switch'], localMaximumPlayers: 2 },
  { id: 74, genre: 'Role-Playing', title: 'Xenoblade Chronicles', releaseYear: 2010, platforms: ['Nintendo Wii'], localMaximumPlayers: 1 },
  { id: 75, genre: 'Strategy', title: 'Fire Emblem: Awakening', releaseYear: 2012, platforms: ['Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 76, genre: 'Role-Playing', title: 'Persona 5', releaseYear: 2016, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 77, genre: 'Role-Playing', title: 'Dragon Quest XI', releaseYear: 2017, platforms: ['PlayStation', 'PC', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 78, genre: 'Action', title: 'Kingdom Hearts', releaseYear: 2002, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 79, genre: 'Role-Playing', title: 'Monster Hunter: World', releaseYear: 2018, platforms: ['PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 1 },
  { id: 80, genre: 'Adventure', title: 'Death Stranding', releaseYear: 2019, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 1 },
  { id: 81, genre: 'Action', title: 'God of War', releaseYear: 2018, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 1 },
  { id: 82, genre: 'Adventure', title: 'The Last of Us', releaseYear: 2013, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 83, genre: 'Adventure', title: 'Uncharted 4: A Thief\'s End', releaseYear: 2016, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 84, genre: 'Action', title: 'Marvel\'s Spider-Man', releaseYear: 2018, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 85, genre: 'Action', title: 'Horizon Zero Dawn', releaseYear: 2017, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 1 },
  { id: 86, genre: 'Action', title: 'Ghost of Tsushima', releaseYear: 2020, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 1 },
  { id: 87, genre: 'Racing', title: 'Forza Horizon 5', releaseYear: 2021, platforms: ['Xbox', 'PC'], localMaximumPlayers: 2 },
  { id: 88, genre: 'Racing', title: 'Need for Speed: Most Wanted', releaseYear: 2005, platforms: ['PlayStation', 'Xbox', 'PC'], localMaximumPlayers: 2 },
  { id: 89, genre: 'Sports', title: 'Tony Hawk\'s Pro Skater 2', releaseYear: 2000, platforms: ['PlayStation', 'PC'], localMaximumPlayers: 2 },
  { id: 90, genre: 'Puzzle', title: 'Undertale', releaseYear: 2015, platforms: ['PC', 'PlayStation', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 91, genre: 'Platformer', title: 'Celeste', releaseYear: 2018, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 92, genre: 'Action', title: 'Hollow Knight', releaseYear: 2017, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 1 },
  { id: 93, genre: 'Platformer', title: 'Cuphead', releaseYear: 2017, platforms: ['PC', 'Xbox', 'PlayStation', 'Nintendo Switch'], localMaximumPlayers: 2 },
  { id: 94, genre: 'Role-Playing', title: 'Dark Souls', releaseYear: 2011, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 95, genre: 'Role-Playing', title: 'Elden Ring', releaseYear: 2022, platforms: ['PC', 'PlayStation', 'Xbox'], localMaximumPlayers: 1 },
  { id: 96, genre: 'Role-Playing', title: 'Bloodborne', releaseYear: 2015, platforms: ['PlayStation'], localMaximumPlayers: 1 },
  { id: 97, genre: 'Social simulation', title: 'Stardew Valley', releaseYear: 2016, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'], localMaximumPlayers: 4 },
  { id: 98, genre: 'Sandbox', title: 'Terraria', releaseYear: 2011, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'], localMaximumPlayers: 4 },
  { id: 99, genre: 'Sports', title: 'Rocket League', releaseYear: 2015, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'], localMaximumPlayers: 4 },
  { id: 100, genre: 'Party', title: 'Among Us', releaseYear: 2018, platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'], localMaximumPlayers: 1 },
];
